services:
  app-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    environment:
      - DB_URL=jdbc:postgresql://postgres-dev:5432/tribal_farm
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DEVELOPMENT=true
    volumes:
      # Mount source code for hot reloading
      - ./src:/app/src
      # Mount build files to avoid rebuilding dependencies
      - ./build.gradle.kts:/app/build.gradle.kts
      - ./settings.gradle.kts:/app/settings.gradle.kts
      - ./gradle.properties:/app/gradle.properties
      # Mount Gradle wrapper to ensure correct version
      - ./gradle/wrapper:/app/gradle/wrapper
      # Mount Gradle cache to speed up builds
      - gradle-cache:/home/gradle/.gradle
    depends_on:
      - postgres-dev
    networks:
      - backend-dev-network

  postgres-dev:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=tribal_farm
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres-dev-data:/var/lib/postgresql/data
    networks:
      - backend-dev-network

networks:
  backend-dev-network:
    driver: bridge

volumes:
  postgres-dev-data:
  gradle-cache:
