FROM openjdk:17-slim

WORKDIR /app

# Copy the source code including gradlew
COPY . /app/

# Make sure gradlew is executable
RUN chmod +x ./gradlew

# Expose the application port
EXPOSE 8080

# Set development flag for Ktor
ENV DEVELOPMENT=true

# Command to run the application with continuous build for hot reloading
CMD ["./gradlew", "run", "-t", "--args='-Dio.ktor.development=true'"]
