ktor:
  application:
    modules:
      - com.bngdev.tribalfarm.ApplicationKt.module
  deployment:
    port: 8080

database:
  driverClass: "org.postgresql.Driver"
  url: ${DB_URL:"jdbc:postgresql://localhost:5432/tribal_farm"}
  user: ${DB_USER:"postgres"}
  password: ${DB_PASSWORD:"postgres"}
  poolSize: 3
  maxPoolSize: 10
  connectionTimeout: 30000
  idleTimeout: 600000
  maxLifetime: 1800000
